version:  '3.7'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - '8080:8080'

  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    volumes:
      - './apps/${APP_NAME}:/var/www/html/symfony:cached'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '${NGINX_PORT}:80'
  
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - './apps/${APP_NAME}:/var/www/html/symfony:cached'
    restart: on-failure
    env_file:
      - .env
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysql
    ports:
      - 8181:80
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - PMA_HOST=mysql
      - PMA_ABSOLUTE_URI=${PMA_ABSOLUTE_URI}


