version:  '3.7'
services:
  mysql:
    image: mysql:5.7
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - '8080:8080'

  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    volumes:
      - './apps/sim_mi_project_dawin/public/:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '${NGINX_PORT}:80'
  
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - './apps/sim_mi_project_dawin:/var/www/html/symfony:cached'
    restart: on-failure
    env_file:
      - .env

